[package]
name = "p34"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p31 = { path = "../p31" }
p35 = { path = "../p35" }
fraction = "0.8.0"